"use client";
import "./globals.css";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Inter } from "next/font/google";
import ScrollComponent from "@/components/scroll.component";
import NavbarComponent from "@/components/navbar.component";
import FooterComponent from "@/components/footer.component";
import { useMouse } from "@mantine/hooks";
import { motion } from "framer-motion";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bijles SR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { ref, x, y } = useMouse();

  return (
    <html
      ref={ref}
      lang="en"
      style={{ scrollBehavior: "smooth", overflowX: "hidden" }}
    >
      <head>
        <ColorSchemeScript />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </head>
      <body className={`${inter.className}`}>
        <MantineProvider>
          <main className="flex min-h-screen flex-col mx-auto items-center">
            <motion.div
              ref={ref}
              className="box"
              animate={{ x: x - 500, y: y - 10 }}
              transition={{
                type: "spring",
                damping: 20,
                stiffness: 30,
                restDelta: 0.001,
              }}
              style={{
                width: "100px",
                height: "100px",
                borderRadius: "50%",
                position: "absolute",
                zIndex: 20,
              }}
            >
              {" "}
              <Image
                src={"/assets/gifs/bee.gif"}
                alt="bee"
                width={30}
                height={30}
              />{" "}
            </motion.div>
            <ScrollComponent>
              <NavbarComponent />
              {children}
              <FooterComponent />
            </ScrollComponent>
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
