import "./globals.css";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Inter } from "next/font/google";
import ScrollComponent from "@/components/scroll.component";
import NavbarComponent from "@/components/navbar.component";
import FooterComponent from "@/components/footer.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth", overflowX: "hidden" }}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${inter.className}`}>
        <MantineProvider>
          <main className="flex min-h-screen flex-col mx-auto items-center">
            <ScrollComponent>
              <NavbarComponent />
              {children}
              <FooterComponent />
            </ScrollComponent>
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
